rating(american_beauty, 84).
rating(anna, 65).
rating(barton_fink, 77).
rating(the_big_lebowski, 81).
rating(blade_runner, 82).
rating(blood_simple, 76).
rating(the_cotton_club, 65).
rating(cq, 63).
rating(crimewave, 58).
rating(down_from_the_mountain, 74).
rating(fargo, 81).
rating(the_firm, 68).
rating(frankenweenie, 70).
rating(ghost_busters, 78).
rating(girl_with_a_pearl_earring, 69).
rating(the_godfather, 92).
rating(the_godfather_part_ii, 90).
rating(the_godfather_part_iii, 76).
rating(groundhog_day, 80).
rating(hail_ceasar, 63).
rating(hearts_of_darkness_a_filmmaker_s_apocalypse, 82).
rating(the_hudsucker_proxy, 73).
rating(inside_monkey_zetterland, 52).
rating(intolerable_cruelty, 63).
rating(the_ladykillers, 62).
rating(lick_the_star, 60).
rating(lost_in_translation, 78).
rating(the_man_who_wasn_t_there, 76).
rating(marie_antoinette, 64).
rating(miller_s_crossing, 78).
rating(mission_impossible, 71).
rating(no_country_for_old_men, 81).
rating(o_brother_where_art_thou, 78).
rating(the_outsiders, 72).
rating(paris_je_t_aime, 73).
rating(peggy_sue_got_married, 63).
rating(raising_arizona, 74).
rating(rumble_fish, 72).
rating(spies_like_us, 64).
rating(star_wars_episode_i__the_phantom_menace, 65).
rating(torrance_rises, 67).
rating(the_usual_suspects, 86).
rating(the_virgin_suicides, 72).
rating(an_american_rhapsody, 68).
rating(the_black_dahlia, 56).
rating(fall, 61).
rating(eight_legged_freaks, 54).
rating(ghost_world, 74).
rating(a_good_woman, 65).
rating(if_lucy_fell, 49).
rating(home_alone_3, 44).
rating(the_horse_whisperer, 66).
rating(in_good_company, 65).
rating(just_cause, 64).
rating(the_island, 69).
rating(a_love_song_for_bobby_long, 72).
rating(manny__lo, 67).
rating(match_point, 76).
rating(my_brother_the_pig, 39).
rating(north, 44).
rating(the_perfect_score, 57).
rating(the_spongebob_squarepants_movie, 70).
rating(untitled_woody_allen_fall_project_2006, 67).
rating(a_view_from_the_bridge, 71).